//! Power BI Desktop command-family capability descriptors.

use serde_json::{Value, json};

pub(super) fn commands() -> Vec<Value> {
    vec![
        json!({
            "path": "desktop open",
            "usage": "powerbi-cli desktop open <project-dir-or.pbip-or.pbix> [--preflight strict|normal|skip] [--timeout-ms <ms>] [--desktop-path <PBIDesktop.exe>] [--enable-oracle] --json",
            "summary": "Open the single CLI-owned interactive Power BI Desktop session, closing a prior owned session first",
            "tags": ["desktop", "session", "lifecycle", "window", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "stability": "alpha-oracle",
            "proofLevel": "unit-smoke",
            "observedStage": "desktop-window",
            "outputSchema": "powerbi-cli.desktop.open.v1",
            "platforms": ["windows session when POWERBI_DESKTOP_ORACLE=1", "linux unsupported_feature", "macos unsupported_feature"],
            "sessionContract": "exactly one CLI-owned session; ownership is persisted outside the project with the exact observed PID and creation time; opening another session first closes only that recorded process lineage",
            "preflightContract": "strict (default) runs PBIP validation plus lint; normal runs PBIP validation without lint; skip runs neither and reports the explicit skip in preflight",
            "flags": ["<project-dir-or.pbip-or.pbix>", "--project <project-dir-or.pbip-or.pbix>", "--preflight strict|normal|skip", "--timeout-ms <ms>", "--desktop-path <PBIDesktop.exe>", "--enable-oracle", "--json", "--format json"],
            "examples": ["POWERBI_DESKTOP_ORACLE=1 powerbi-cli desktop open build/sales --json", "powerbi-cli desktop open build/sales --enable-oracle --json", "POWERBI_DESKTOP_ORACLE=1 powerbi-cli desktop open build/sales --preflight normal --json", "POWERBI_DESKTOP_ORACLE=1 powerbi-cli desktop open SourceProfile.pbix --json"],
            "followUpFields": ["ok", "exitCode", "document.kind", "document.path", "preflight.mode", "preflight.performed", "preflight.skipped", "preflight.ok", "session.state", "session.owned", "session.desktopProcessId", "session.desktopProcessCreationTimeUtc", "session.receiptPath", "session.cleanupCommand", "session.priorSessionCleanup", "proof", "validation", "diagnostics", "next"]
        }),
        json!({
            "path": "desktop close",
            "usage": "powerbi-cli desktop close --json",
            "summary": "Idempotently close only the exact CLI-owned Power BI Desktop session and its verified descendants",
            "tags": ["desktop", "session", "lifecycle", "cleanup", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "stability": "alpha-oracle",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.desktop.close.v1",
            "platforms": ["windows", "linux unsupported_feature", "macos unsupported_feature"],
            "sessionContract": "idempotent; a missing, exited, or PID-reused receipt returns alreadyClosed without killing anything; failed verified cleanup retains the receipt for retry",
            "flags": ["--json", "--format json"],
            "examples": ["powerbi-cli desktop close --json"],
            "followUpFields": ["ok", "exitCode", "session.state", "session.alreadyClosed", "session.document", "session.documentKind", "session.desktopProcessId", "session.receiptPath", "session.receiptRemoved", "cleanup.attempted", "cleanup.identityMatched", "cleanup.closed", "cleanup.targeted", "cleanup.remainingProcessIds", "cleanup.errors", "next"]
        }),
        json!({
            "path": "desktop open-check",
            "usage": "powerbi-cli desktop open-check <project-dir-or.pbip-or.pbix> [--timeout-ms <ms>] [--desktop-path <PBIDesktop.exe>] [--enable-oracle] --json",
            "summary": "Attempt one-shot Power BI Desktop launch plus exact project-title observation, then clean up",
            "tags": ["desktop", "oracle", "proof", "window", "title", "windows", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-oracle",
            "proofLevel": "unit-smoke",
            "observedStage": "desktop-window",
            "outputSchema": "powerbi-cli.desktop.openCheck.v1",
            "platforms": ["windows observation when POWERBI_DESKTOP_ORACLE=1", "linux unsupported_feature", "macos unsupported_feature"],
            "ciPolicy": "never required in default CI; run only on Windows with POWERBI_DESKTOP_ORACLE=1 and Desktop installed; proof.observedStage reports launch/exact-title observations and is not a canvas/render/refresh compatibility claim",
            "timeoutContract": "timeout-ms is one watchdog budget for the bounded version probe, process baseline, file-association launch, and exact window/title polling; a timeout after confirmed launch returns exit 0 with observedStage=desktop-launch and timeout signals, while a launch timeout is oracle_failed",
            "flags": ["<project-dir-or.pbip-or.pbix>", "--project <project-dir-or.pbip-or.pbix>", "--timeout-ms <ms>", "--desktop-path <PBIDesktop.exe>", "--enable-oracle", "--json", "--format json"],
            "examples": ["powerbi-cli desktop open-check build/sales --json", "powerbi-cli desktop open-check build/sales --enable-oracle --json", "POWERBI_DESKTOP_ORACLE=1 powerbi-cli desktop open-check build/sales --desktop-path \"C:\\\\Program Files\\\\Microsoft Power BI Desktop\\\\bin\\\\PBIDesktop.exe\" --json"],
            "followUpFields": ["ok", "exitCode", "changes", "oracle.available", "oracle.desktopVersion", "oracle.detection.requestedDesktopPath", "proof.level", "proof.observedStage", "proof.status", "proof.passed", "proof.signals.launchMethod", "proof.signals.detectionPathUsedForLaunch", "proof.signals.windowObserved", "proof.signals.titleMatched", "proof.signals.observedWindowTitle", "proof.signals.windowSelectionReason", "proof.signals.observation", "proof.signals.observation.exactTitleCandidateCount", "proof.signals.cleanup", "proof.signals.cleanup.targeted", "proof.claimedCompatibility", "proof.requiredCompatibilityLevel", "proof.unprovenSignals", "proof.manualReview", "validation", "diagnostics", "next"]
        }),
        json!({
            "path": "desktop screenshot",
            "usage": "powerbi-cli desktop screenshot <project-dir-or.pbip-or.pbix> --out <file.png> [--timeout-ms <ms>] [--desktop-path <PBIDesktop.exe>] [--allow-unverified-capture] [--enable-oracle] --json",
            "summary": "Capture the primary display after exact Desktop title and foreground-PID verification for manual or agent review",
            "tags": ["desktop", "oracle", "proof", "window", "title", "screenshot", "evidence", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "writesEvidenceArtifact": true,
            "stability": "alpha-oracle",
            "proofLevel": "unit-smoke",
            "observedStage": "desktop-window",
            "outputSchema": "powerbi-cli.desktop.screenshot.v1",
            "platforms": ["windows evidence capture when POWERBI_DESKTOP_ORACLE=1", "linux unsupported_feature", "macos unsupported_feature"],
            "ciPolicy": "never required in default CI; screenshots are evidence for manual/screen-agent review and never an automated canvas/render/refresh compatibility claim",
            "timeoutContract": "timeout-ms is one watchdog budget for the bounded version probe, process baseline, file-association launch, and exact window/title polling; if launch succeeds but no exact project title appears, screenshot returns proof_incomplete exit 20 rather than oracle_failed",
            "outputPathPolicy": "--out must end in .png and resolve outside the PBIP project directory; capture uses a unique same-directory temporary file and creates/replaces the destination only after success",
            "captureSafety": "foreground PID must be the selected PBIDesktop process or one of its verified descendants; failure publishes no PNG. --allow-unverified-capture explicitly accepts the risk of capturing unrelated sensitive screen content",
            "flags": ["<project-dir-or.pbip-or.pbix>", "--project <project-dir-or.pbip-or.pbix>", "--out <file.png>", "--timeout-ms <ms>", "--desktop-path <PBIDesktop.exe>", "--allow-unverified-capture", "--enable-oracle", "--json", "--format json"],
            "examples": ["powerbi-cli desktop screenshot build/sales --out proof/sales.png --json"],
            "followUpFields": ["ok", "exitCode", "changes", "oracle.available", "oracle.desktopVersion", "proof.level", "proof.observedStage", "proof.status", "proof.claimedCompatibility", "proof.signals.windowObserved", "proof.signals.titleMatched", "proof.signals.observedWindowTitle", "proof.signals.windowSelectionReason", "proof.signals.observation", "proof.signals.observation.exactTitleCandidateCount", "proof.signals.screenshotCaptured", "proof.signals.screenshotPath", "proof.signals.screenshotActivationSucceeded", "proof.signals.screenshotForegroundVerified", "proof.signals.screenshotForegroundProcessId", "proof.signals.cleanup", "proof.signals.cleanup.targeted", "screenshot.path", "screenshot.captured", "screenshot.activationSucceeded", "screenshot.foregroundVerified", "screenshot.foregroundProcessId", "screenshot.allowUnverifiedCapture", "screenshot.purpose", "screenshot.automatedCompatibilityProof", "diagnostics", "next"]
        }),
        json!({
            "path": "desktop refresh-check",
            "usage": "powerbi-cli desktop refresh-check <project-dir-or.pbip-or.pbix> [--timeout-ms <ms>] [--desktop-path <PBIDesktop.exe>] [--enable-oracle] --json",
            "summary": "Planned Windows Desktop refresh proof that will verify dummy-partition refresh and issue-dialog absence",
            "tags": ["desktop", "oracle", "proof", "refresh", "windows", "planned", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "planned",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.desktop.refreshCheck.v1",
            "platforms": ["windows when T9.1 is available", "linux unsupported_feature", "macos unsupported_feature"],
            "flags": ["<project-dir-or.pbip-or.pbix>", "--project <project-dir-or.pbip-or.pbix>", "--timeout-ms <ms>", "--desktop-path <PBIDesktop.exe>", "--enable-oracle", "--json", "--format json"],
            "limitations": ["T9.1 is not implemented in this release; the command is advertised so proof plans remain forward-compatible and returns unsupported_feature until the Windows oracle implementation lands."],
            "followUpFields": ["ok", "exitCode", "project", "refresh.completed", "refresh.errors", "proof", "diagnostics", "next"]
        }),
        json!({
            "path": "desktop canvas-check",
            "usage": "powerbi-cli desktop canvas-check <project-dir-or.pbip-or.pbix> --page <page> --expect <values.json> [--timeout-ms <ms>] [--desktop-path <PBIDesktop.exe>] [--enable-oracle] --json",
            "summary": "Planned Windows Desktop canvas proof that will assert expected values and reject a blank rendered page",
            "tags": ["desktop", "oracle", "proof", "canvas", "refresh", "windows", "planned", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "planned",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.desktop.canvasCheck.v1",
            "platforms": ["windows when T9.2 is available", "linux unsupported_feature", "macos unsupported_feature"],
            "flags": ["<project-dir-or.pbip-or.pbix>", "--project <project-dir-or.pbip-or.pbix>", "--page <page>", "--expect <values.json>", "--timeout-ms <ms>", "--desktop-path <PBIDesktop.exe>", "--enable-oracle", "--json", "--format json"],
            "limitations": ["T9.2 is not implemented in this release; the command is advertised so proof plans remain forward-compatible and returns unsupported_feature until the Windows oracle implementation lands."],
            "followUpFields": ["ok", "exitCode", "project", "page", "expectations", "canvas.rendered", "canvas.blankRejected", "proof", "diagnostics", "next"]
        }),
        json!({
            "path": "desktop bridge status",
            "usage": "powerbi-cli desktop bridge status [--pid <pid>] --json",
            "summary": "Inspect pinned Microsoft Desktop Bridge instances and their exact current-file, dirty-state, and PBIR page inventory",
            "tags": ["desktop", "bridge", "microsoft", "preview", "status", "windows", "agent"],
            "readOnly": true,
            "mutates": false,
            "networkRequired": false,
            "stability": "preview-output",
            "proofLevel": "unit-smoke",
            "observedStage": "state-inventory",
            "outputSchema": "powerbi-cli.desktop.bridge.status.v1",
            "platforms": ["windows", "linux unsupported_feature", "macos unsupported_feature"],
            "flags": ["--pid <pid>", "--json", "--format json"],
            "examples": ["powerbi-cli desktop bridge status --json", "powerbi-cli desktop bridge status --pid 1234 --json"],
            "limitations": ["Bridge state and page inventory do not prove report refresh, rendered correctness, save/reopen, interactions, drill behavior, issue-dialog absence, or semantic correctness."],
            "followUpFields": ["ok", "exitCode", "ready", "status", "instances[].pid", "instances[].bridgeStatus", "instances[].currentFilePath", "instances[].hasUnsavedChanges", "instances[].pages", "backend.version", "backend.stdoutSha256", "proof", "next"]
        }),
        json!({
            "path": "desktop bridge reload",
            "usage": "powerbi-cli desktop bridge reload --project <project-dir-or.pbip> --pid <pid> --json",
            "summary": "Reload the report definition only after exact canonical project/PID identity and a clean saved Desktop state are proven",
            "tags": ["desktop", "bridge", "microsoft", "preview", "reload", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "networkRequired": false,
            "stability": "preview-output",
            "proofLevel": "unit-smoke",
            "observedStage": "reload-request-completed",
            "outputSchema": "powerbi-cli.desktop.bridge.reload.v1",
            "platforms": ["windows", "linux unsupported_feature", "macos unsupported_feature"],
            "flags": ["--project <project-dir-or.pbip>", "--pid <pid>", "--json", "--format json"],
            "examples": ["powerbi-cli desktop bridge reload --project build/sales --pid 1234 --json"],
            "limitations": ["Reload uses reloadModelDefinition=false and is refused for dirty or non-exact instances. Completion does not prove refresh, save/reopen, rendered correctness, interactions, drill behavior, issue-dialog absence, or semantic correctness."],
            "followUpFields": ["ok", "exitCode", "project", "pid", "hasUnsavedChanges", "ownership.owned", "ownership.cleanupEligible", "desktop.desktopVersion", "backend.version", "changes", "proof", "next"]
        }),
        json!({
            "path": "desktop bridge screenshot-page",
            "usage": "powerbi-cli desktop bridge screenshot-page --project <project-dir-or.pbip> --pid <pid> --page <id> --out <new.png> --json",
            "summary": "Capture one exact inventoried PBIR page through the pinned Desktop Bridge into a new guarded PNG evidence file",
            "tags": ["desktop", "bridge", "microsoft", "preview", "screenshot", "evidence", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "writesEvidenceArtifact": true,
            "networkRequired": false,
            "stability": "preview-output",
            "proofLevel": "unit-smoke",
            "observedStage": "page-screenshot-captured",
            "outputSchema": "powerbi-cli.desktop.bridge.screenshotPage.v1",
            "platforms": ["windows", "linux unsupported_feature", "macos unsupported_feature"],
            "outputPathPolicy": "--out must be a new .png outside the PBIP project; existing evidence is never replaced or deleted",
            "flags": ["--project <project-dir-or.pbip>", "--pid <pid>", "--page <id>", "--out <new.png>", "--json", "--format json"],
            "examples": ["powerbi-cli desktop bridge screenshot-page --project build/sales --pid 1234 --page ReportSection --out proof/page.png --json"],
            "limitations": ["A dirty-instance capture is labeled diagnostic and cannot represent on-disk workflow output. PNG capture does not prove refresh, save/reopen, interactions, drill behavior, issue-dialog absence, or semantic correctness."],
            "followUpFields": ["ok", "exitCode", "project", "pid", "page", "hasUnsavedChanges", "screenshot.path", "screenshot.width", "screenshot.height", "screenshot.bytes", "screenshot.sha256", "ownership", "desktop.desktopVersion", "backend", "proof", "next"]
        }),
        json!({
            "path": "desktop bridge screenshot-all",
            "usage": "powerbi-cli desktop bridge screenshot-all --project <project-dir-or.pbip> --pid <pid> --out-dir <new-dir> --json",
            "summary": "Capture the exact bounded Desktop status page inventory through the pinned Bridge into a new guarded directory",
            "tags": ["desktop", "bridge", "microsoft", "preview", "screenshot", "pages", "evidence", "windows", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "writesEvidenceArtifact": true,
            "networkRequired": false,
            "stability": "preview-output",
            "proofLevel": "unit-smoke",
            "observedStage": "all-page-screenshots-captured",
            "outputSchema": "powerbi-cli.desktop.bridge.screenshotAll.v1",
            "platforms": ["windows", "linux unsupported_feature", "macos unsupported_feature"],
            "outputPathPolicy": "--out-dir must not exist and must be outside the PBIP project; existing evidence is never replaced or deleted",
            "flags": ["--project <project-dir-or.pbip>", "--pid <pid>", "--out-dir <new-dir>", "--json", "--format json"],
            "examples": ["powerbi-cli desktop bridge screenshot-all --project build/sales --pid 1234 --out-dir proof/pages --json"],
            "limitations": ["Capture inventory must equal the bounded status inventory. Dirty-instance captures are diagnostic and cannot represent on-disk workflow output. Screenshots do not prove refresh, save/reopen, interactions, drill behavior, issue-dialog absence, or semantic correctness."],
            "followUpFields": ["ok", "exitCode", "project", "pid", "hasUnsavedChanges", "pageInventory", "screenshots[].pageId", "screenshots[].file.path", "screenshots[].file.width", "screenshots[].file.height", "screenshots[].file.sha256", "outputDirectory", "ownership", "desktop.desktopVersion", "backend", "proof", "next"]
        }),
        json!({
            "path": "desktop harvest-reference",
            "usage": "powerbi-cli desktop harvest-reference --project <saved.pbip> --visual <visual:<page>:<name>|page:<name>|report:main> --out docs/reference/desktop-authored-visuals/<name>.json [--desktop-version <version>] [--license-note <text>] [--dry-run] --json",
            "summary": "Archive one Desktop-saved visual, page, or report fragment with source fingerprint, date, license note, and honest pending proof",
            "tags": ["desktop", "oracle", "fixture", "reference", "provenance", "offline", "agent"],
            "readOnly": false,
            "mutates": true,
            "mutatesProject": false,
            "writesReferenceArtifact": true,
            "networkRequired": false,
            "stability": "alpha-output",
            "proofLevel": "desktop-golden-pending",
            "observedStage": "reference-archived",
            "outputSchema": "powerbi-cli.desktop.harvestReference.v1",
            "platforms": ["linux already-saved PBIP", "macos already-saved PBIP", "windows already-saved PBIP; Desktop execution evidence is optional and never inferred"],
            "inputSafety": "The selected visual.json, page.json, or report.json is read through input_safety::read_harvested_fragment. Persisted selection/filter values, symlinks, invalid UTF-8, oversized files, and malformed JSON are refused; no rejected value is silently stripped.",
            "proofContract": "Linux and non-oracle runs record desktopVersion=unknown and proofLevel=desktop-golden-pending. A harvested reference is never promoted to a Desktop canvas/refresh proof without explicit evidence.",
            "flags": ["--project <saved.pbip>", "--visual <visual:<page>:<name>|page:<name>|report:main>", "--out <reference.json>", "--desktop-version <version>", "--license-note <text>", "--dry-run", "--json", "--format json"],
            "examples": ["powerbi-cli desktop harvest-reference --project build/sales --visual visual:ReportSectionOverview:VisualContainer1 --out docs/reference/desktop-authored-visuals/sales-card.json --json", "powerbi-cli desktop harvest-reference --project build/sales.pbip --visual page:ReportSectionOverview --out docs/reference/desktop-authored-visuals/overview-page.json --dry-run --json"],
            "limitations": ["The archive wraps the source fragment under fragment and keeps provenance separate from PBIR fields.", "Already-saved Linux projects have no Desktop version or canvas evidence unless supplied explicitly; the output remains desktop-golden-pending.", "Persisted slicer/filter values are refused rather than silently removed; use a clean saved fragment or clear state in Desktop before retrying."],
            "followUpFields": ["ok", "exitCode", "action", "dryRun", "projectDir", "pbip", "reportDir", "out", "source.kind", "source.handle", "source.path", "source.sha256", "source.sourceFingerprint", "destination.path", "destination.name", "destination.created", "provenance.sourcePath", "provenance.sourceProject", "provenance.desktopVersion", "provenance.date", "provenance.sourceFingerprint", "provenance.fragmentSha256", "provenance.licenseNote", "proofLevel", "proof.schema", "proof.fixture", "proof.signals.featureIds", "proof.signals.desktopReferencePresent", "proof.signals.schemaGolden", "safety.persistedDataValues", "safety.silentStripping", "changes", "next", "notes", "warnings", "errors"]
        }),
    ]
}
