//! Semantic-model command-family capability descriptors.

use serde_json::{Value, json};

pub(super) fn commands() -> Vec<Value> {
    vec![
        json!({
            "path": "model tables add-static",
            "aliases": ["model tables add-selector"],
            "usage": "powerbi-cli model tables add-static --project <project-dir-or.pbip> --table <table> ((--column <column> --values-json <json-array-of-strings>) | (--columns-json <json-array-of-column-names> --rows-json <json-array-of-string-arrays>)) [--include-raw] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Add a small static selector table or multi-column lookup dimension backed by an inline M table",
            "tags": ["tmdl", "semantic-model", "table", "static-table", "selector", "parameter", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.tables.staticMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--column <column>", "--values-json <json-array-of-strings>", "--columns-json <json-array-of-column-names>", "--rows-json <json-array-of-string-arrays>", "--include-raw", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model tables add-static --project build/sales --table Metric --column Metric --values-json '[\"Count\",\"Cost\"]' --dry-run --json", "powerbi-cli model tables add-static --project build/sales --table DimSegment --columns-json '[\"Code\",\"Label\"]' --rows-json '[[\"A\",\"Alpha\"],[\"B\",\"Beta\"]]' --dry-run --json"],
            "limitations": ["Creates only a new table with 1-10 string columns and 1-100 short rows; the first column must be unique.", "Does not create relationships automatically; add the reviewed relationship separately with model relationships add.", "Refuses replacement, credentials, multiline cells, duplicate rows/keys, and arbitrary fact-table ingestion."],
            "followUpFields": ["dryRun", "projectModified", "target.handle", "target.columns", "tablePlan.columnCount", "tablePlan.rowCount", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model columns set-sort-by",
            "usage": "powerbi-cli model columns set-sort-by --project <project-dir-or.pbip> --table <table> --column <column> (--by <sort-column> | --clear) (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Set or remove one column's same-table TMDL sortByColumn property with guarded output semantics",
            "tags": ["tmdl", "semantic-model", "column", "sort", "sortByColumn", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.columns.setSortBy.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--column <column>", "--by <sort-column>", "--clear", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model columns set-sort-by --project build/sales --table DimDate --column Month --by MonthNumber --dry-run --json", "powerbi-cli model columns set-sort-by --project build/sales --table DimDate --column Month --clear --dry-run --json"],
            "limitations": ["Both target and sort columns must exist in the same table; a column cannot sort by itself.", "The command edits only sortByColumn and preserves all other TMDL bytes."],
            "followUpFields": ["ok", "dryRun", "mode", "projectModified", "target.handle", "target.sortByColumn", "target.previousSortByColumn", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model calculated-columns list",
            "usage": "powerbi-cli model calculated-columns list --project <project-dir-or.pbip> [--table <table>] --json",
            "summary": "List semantic model DAX calculated columns with stable column handles",
            "tags": ["tmdl", "semantic-model", "calculated-column", "column", "dax", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelCalculatedColumnsList.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--json", "--format json"],
            "examples": ["powerbi-cli model calculated-columns list --project build/sales --json", "powerbi-cli model calculated-columns list --project build/sales --table FactSales --json"],
            "followUpFields": ["calculatedColumns[].handle", "calculatedColumns[].expression", "next"]
        }),
        json!({
            "path": "model calculated-columns show",
            "usage": "powerbi-cli model calculated-columns show --project <project-dir-or.pbip> (--handle <column-handle> | --table <table> --name <column>) --json",
            "summary": "Show one semantic model DAX calculated column and its TMDL block",
            "tags": ["tmdl", "semantic-model", "calculated-column", "column", "dax", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelCalculatedColumnsShow.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <column-handle>", "--table <table>", "--name <column>", "--json", "--format json"],
            "examples": ["powerbi-cli model calculated-columns show --project build/sales --handle 'column:FactSales:Revenue Band' --json"],
            "followUpFields": ["calculatedColumn.handle", "calculatedColumn.expression", "block", "next"]
        }),
        json!({
            "path": "model calculated-columns add",
            "usage": "powerbi-cli model calculated-columns add --project <project-dir-or.pbip> --table <table> --name <column> (--expression <dax> | --expression-file <path|->) --data-type <type> [--format-string <fmt>] [--summarize-by <mode>] [--display-folder <folder>] [--description <text>] [--hidden] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Add a DAX calculated column to a TMDL table with guarded output semantics",
            "tags": ["tmdl", "semantic-model", "calculated-column", "column", "dax", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelCalculatedColumnsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--name <column>", "--expression <dax>", "--expression-file <path|->", "--data-type <type>", "--format-string <fmt>", "--summarize-by <mode>", "--display-folder <folder>", "--description <text>", "--hidden", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model calculated-columns add --project build/sales --table FactSales --name 'Revenue Band' --expression 'IF(''FactSales''[Revenue] >= 10000, \"\"High\"\", \"\"Standard\"\")' --data-type string --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model calculated-columns update",
            "usage": "powerbi-cli model calculated-columns update --project <project-dir-or.pbip> (--handle <column-handle> | --table <table> --name <column>) [--expression <dax> | --expression-file <path|->] [--data-type <type>] [--format-string <fmt>] [--summarize-by <mode>] [--display-folder <folder>] [--description <text>] [--hidden|--visible] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Update a DAX calculated column expression or metadata; refuses unsupported Desktop-authored TMDL lines",
            "tags": ["tmdl", "semantic-model", "calculated-column", "column", "dax", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelCalculatedColumnsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <column-handle>", "--table <table>", "--name <column>", "--expression <dax>", "--expression-file <path|->", "--data-type <type>", "--format-string <fmt>", "--summarize-by <mode>", "--display-folder <folder>", "--description <text>", "--hidden", "--visible", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model calculated-columns update --project build/sales --handle 'column:FactSales:Revenue Band' --expression 'IF(''FactSales''[Revenue] >= 5000, \"\"High\"\", \"\"Standard\"\")' --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model calculated-columns delete",
            "usage": "powerbi-cli model calculated-columns delete --project <project-dir-or.pbip> (--handle <column-handle> | --table <table> --name <column>) (--dry-run | --in-place --confirm <column-handle> | --out-dir <dir>) --json",
            "summary": "Delete a DAX calculated column; in-place delete requires exact handle confirmation",
            "tags": ["tmdl", "semantic-model", "calculated-column", "column", "dax", "mutation", "delete", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "confirmRequiredForInPlace": true,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelCalculatedColumnsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <column-handle>", "--table <table>", "--name <column>", "--dry-run", "--in-place", "--confirm <column-handle>", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model calculated-columns delete --project build/sales --handle 'column:FactSales:Revenue Band' --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model measures list",
            "usage": "powerbi-cli model measures list --project <project-dir-or.pbip> [--table <table>] --json",
            "summary": "List semantic model DAX measures with stable handles",
            "tags": ["tmdl", "semantic-model", "measure", "dax", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelMeasuresList.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--json", "--format json"],
            "examples": ["powerbi-cli model measures list --project build/sales --json", "powerbi-cli model measures list --project build/sales --table FactSales --json"],
            "followUpFields": ["measures[].handle", "measures[].expression", "next"]
        }),
        json!({
            "path": "model measures show",
            "usage": "powerbi-cli model measures show --project <project-dir-or.pbip> (--handle <measure-handle> | --table <table> --name <measure>) --json",
            "summary": "Show one semantic model DAX measure and its TMDL block",
            "tags": ["tmdl", "semantic-model", "measure", "dax", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelMeasuresShow.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <measure-handle>", "--table <table>", "--name <measure>", "--json", "--format json"],
            "examples": ["powerbi-cli model measures show --project build/sales --handle 'measure:FactSales:Total Revenue' --json"],
            "followUpFields": ["measure.handle", "measure.expression", "block", "next"]
        }),
        json!({
            "path": "model measures add",
            "usage": "powerbi-cli model measures add --project <project-dir-or.pbip> --table <table> --name <measure> (--expression <dax> | --expression-file <path|->) [--format-string <fmt> | --format-string-definition <dax>] [--display-folder <folder>] [--description <text>] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Add a DAX measure from inline text or a UTF-8 expression file to a TMDL table with guarded output semantics",
            "tags": ["tmdl", "semantic-model", "measure", "dax", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelMeasuresMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--name <measure>", "--expression <dax>", "--expression-file <path|->", "--format-string <fmt>", "--format-string-definition <dax>", "--display-folder <folder>", "--description <text>", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model measures add --project build/sales --table FactSales --name 'Average Revenue' --expression 'DIVIDE([Total Revenue], [Total Units])' --dry-run --json"],
            "limitations": ["--expression and --expression-file are mutually exclusive; expression files are UTF-8 and trailing CR/LF bytes are trimmed."],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model measures update",
            "usage": "powerbi-cli model measures update --project <project-dir-or.pbip> (--handle <measure-handle> | --table <table> --name <measure>) [--expression <dax> | --expression-file <path|->] [--format-string <fmt> | --format-string-definition <dax>] [--display-folder <folder>] [--description <text>] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Update a DAX measure from inline text or a UTF-8 expression file; refuses unsupported Desktop-authored TMDL lines",
            "tags": ["tmdl", "semantic-model", "measure", "dax", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelMeasuresMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <measure-handle>", "--table <table>", "--name <measure>", "--expression <dax>", "--expression-file <path|->", "--format-string <fmt>", "--format-string-definition <dax>", "--display-folder <folder>", "--description <text>", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model measures update --project build/sales --handle 'measure:FactSales:Total Revenue' --expression 'SUM(''FactSales''[Revenue])' --dry-run --json"],
            "limitations": ["--expression and --expression-file are mutually exclusive; expression files are UTF-8 and trailing CR/LF bytes are trimmed.", "--format-string and --format-string-definition are mutually exclusive; setting one clears the other. Dynamic format strings are single-line DAX."],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model measures delete",
            "usage": "powerbi-cli model measures delete --project <project-dir-or.pbip> (--handle <measure-handle> | --table <table> --name <measure>) (--dry-run | --in-place --confirm <measure-handle> | --out-dir <dir>) --json",
            "summary": "Delete a DAX measure; in-place delete requires exact handle confirmation",
            "tags": ["tmdl", "semantic-model", "measure", "dax", "mutation", "delete", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "confirmRequiredForInPlace": true,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelMeasuresMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <measure-handle>", "--table <table>", "--name <measure>", "--dry-run", "--in-place", "--confirm <measure-handle>", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model measures delete --project build/sales --handle 'measure:FactSales:Average Revenue' --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model relationships list",
            "usage": "powerbi-cli model relationships list --project <project-dir-or.pbip> [--table <table>] --json",
            "summary": "List semantic model relationships with stable relationship handles and endpoint column handles",
            "tags": ["tmdl", "semantic-model", "relationship", "model", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelRelationshipsList.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--json", "--format json"],
            "examples": ["powerbi-cli model relationships list --project build/sales --json", "powerbi-cli model relationships list --project build/sales --table FactSales --json"],
            "followUpFields": ["relationships[].handle", "relationships[].from.columnHandle", "relationships[].to.columnHandle", "next"]
        }),
        json!({
            "path": "model relationships show",
            "usage": "powerbi-cli model relationships show --project <project-dir-or.pbip> (--handle <relationship-handle> | --name <relationship-name>) --json",
            "summary": "Show one semantic model relationship, endpoints, properties, and its TMDL block",
            "tags": ["tmdl", "semantic-model", "relationship", "model", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelRelationshipsShow.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <relationship-handle>", "--name <relationship-name>", "--json", "--format json"],
            "examples": ["powerbi-cli model relationships show --project build/sales --handle <relationship-handle> --json"],
            "followUpFields": ["relationship.handle", "relationship.from", "relationship.to", "relationship.properties", "block", "next"]
        }),
        json!({
            "path": "model relationships add",
            "usage": "powerbi-cli model relationships add --project <project-dir-or.pbip> --from-table <table> --from-column <column> --to-table <table> --to-column <column> [--name <relationship-name>] [--from-cardinality <one|many>] [--to-cardinality <one|many>] [--cross-filtering-behavior <oneDirection|bothDirections|automatic>] [--inactive] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Add a semantic model relationship with explicit endpoints and guarded output semantics",
            "tags": ["tmdl", "semantic-model", "relationship", "model", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelRelationshipsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--from-table <table>", "--from-column <column>", "--to-table <table>", "--to-column <column>", "--name <relationship-name>", "--from-cardinality <one|many>", "--to-cardinality <one|many>", "--cross-filtering-behavior <mode>", "--cross-filter <mode>", "--active", "--inactive", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model relationships add --project build/sales --from-table FactSales --from-column DateKey --to-table DimDate --to-column DateKey --cross-filtering-behavior oneDirection --dry-run --json", "powerbi-cli model relationships add --project build/sales --from-table FactSales --from-column RegionCode --to-table DimRegion --to-column RegionCode --to-cardinality many --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model relationships update",
            "usage": "powerbi-cli model relationships update --project <project-dir-or.pbip> (--handle <relationship-handle> | --name <relationship-name>) [--from-cardinality <one|many>] [--to-cardinality <one|many>] [--cross-filtering-behavior <oneDirection|bothDirections|automatic>] [--active|--inactive] (--dry-run | --in-place | --out-dir <dir>) --json",
            "summary": "Update relationship active state, cardinality, or cross-filtering behavior; endpoint rewiring is delete+add",
            "tags": ["tmdl", "semantic-model", "relationship", "model", "mutation", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelRelationshipsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <relationship-handle>", "--name <relationship-name>", "--from-cardinality <one|many>", "--to-cardinality <one|many>", "--cross-filtering-behavior <mode>", "--cross-filter <mode>", "--active", "--inactive", "--dry-run", "--in-place", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model relationships update --project build/sales --handle <relationship-handle> --cross-filtering-behavior bothDirections --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model relationships delete",
            "usage": "powerbi-cli model relationships delete --project <project-dir-or.pbip> (--handle <relationship-handle> | --name <relationship-name>) (--dry-run | --in-place --confirm <relationship-handle> | --out-dir <dir>) --json",
            "summary": "Delete a semantic model relationship; in-place delete requires exact handle confirmation",
            "tags": ["tmdl", "semantic-model", "relationship", "model", "mutation", "delete", "agent"],
            "readOnly": false,
            "mutates": true,
            "requiresOutput": true,
            "writesDataCache": false,
            "confirmRequiredForInPlace": true,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelRelationshipsMutation.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <relationship-handle>", "--name <relationship-name>", "--dry-run", "--in-place", "--confirm <relationship-handle>", "--out-dir <dir>", "--json", "--format json"],
            "examples": ["powerbi-cli model relationships delete --project build/sales --handle <relationship-handle> --dry-run --json"],
            "followUpFields": ["dryRun", "projectModified", "rollback.performed", "changes[].before", "changes[].after", "readbackCommand", "inspectCommand", "validateCommand"]
        }),
        json!({
            "path": "model partitions list",
            "usage": "powerbi-cli model partitions list --project <project-dir-or.pbip> [--table <table>] --json",
            "summary": "List semantic model partitions with source kind and offline safety classification",
            "tags": ["tmdl", "semantic-model", "partition", "model", "handoff", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelPartitionsList.v1",
            "flags": ["--project <project-dir-or.pbip>", "--table <table>", "--json", "--format json"],
            "examples": ["powerbi-cli model partitions list --project build/sales --json", "powerbi-cli model partition list --project build/sales --table FactSales --json"],
            "followUpFields": ["partitions[].handle", "partitions[].sourceKind", "partitions[].offlineSafety", "next"]
        }),
        json!({
            "path": "model partitions show",
            "usage": "powerbi-cli model partitions show --project <project-dir-or.pbip> (--handle <partition-handle> | --table <table> --name <partition-name>) [--include-source] --json",
            "summary": "Show one semantic model partition with a redacted preview by default; raw source/block output requires --include-source and is refused unless safety is safe",
            "tags": ["tmdl", "semantic-model", "partition", "model", "handoff", "agent"],
            "readOnly": true,
            "mutates": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "modelPartitionsShow.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <partition-handle>", "--table <table>", "--name <partition-name>", "--partition <partition-name>", "--include-source", "--json", "--format json"],
            "examples": ["powerbi-cli model partitions show --project build/sales --handle partition:FactSales:FactSales --json"],
            "followUpFields": ["partition.handle", "partition.sourcePreview", "partition.source", "partition.sourceIncluded", "partition.offlineSafety", "block", "next"]
        }),
        json!({
            "path": "model dax bridge-plan",
            "aliases": ["model dax plan", "model dax validate-plan"],
            "usage": "powerbi-cli model dax bridge-plan --project <project-dir-or.pbip> [--engine desktop|xmla|tabular-editor] --json",
            "summary": "Inventory DAX measures/calculated columns and return the external validation bridge boundary without fake local DAX compatibility claims",
            "tags": ["tmdl", "semantic-model", "dax", "measure", "calculated-column", "validation", "bridge", "oracle", "agent", "no-fallback"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.dax.bridgePlan.v1",
            "flags": ["--project <project-dir-or.pbip>", "--engine desktop|xmla|tabular-editor", "--json", "--format json"],
            "examples": ["powerbi-cli model dax bridge-plan --project build/sales --json", "powerbi-cli model dax bridge-plan --project build/sales --engine desktop --json"],
            "followUpFields": ["ok", "projectDir", "counts.measures", "counts.calculatedColumns", "daxInventory.measures[].handle", "daxInventory.calculatedColumns[].handle", "bridge.required", "bridge.supportedEngines", "bridge.noFakeFallbacks", "validationBridge.offlineDaxParser.available", "next"]
        }),
        json!({
            "path": "model dax dependencies",
            "aliases": ["model dax references", "model dax refs"],
            "usage": "powerbi-cli model dax dependencies --project <project-dir-or.pbip> --json",
            "summary": "Extract static DAX table/column and measure references for dependency graphing without claiming DAX-engine validation",
            "tags": ["tmdl", "semantic-model", "dax", "dependencies", "references", "lint", "agent", "no-fallback"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.dax.dependencies.v1",
            "flags": ["--project <project-dir-or.pbip>", "--json", "--format json"],
            "examples": ["powerbi-cli model dax dependencies --project build/sales --json"],
            "limitations": ["Static reference extraction only; not a full DAX parser.", "Use model dax bridge-plan for Desktop/XMLA/Tabular Editor validation boundaries."],
            "followUpFields": ["analysisBoundary.daxEngineValidated", "counts", "expressions[].tableColumns", "expressions[].measureReferences", "graph.edges", "findings", "next"]
        }),
        json!({
            "path": "model dax lint",
            "aliases": ["model dax check"],
            "usage": "powerbi-cli model dax lint --project <project-dir-or.pbip> --json",
            "summary": "Run static DAX reference lint for missing columns/measures, ambiguous measure names, self references, and measure dependency cycles",
            "tags": ["tmdl", "semantic-model", "dax", "lint", "bpa", "agent", "no-fallback"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.dax.lint.v1",
            "flags": ["--project <project-dir-or.pbip>", "--json", "--format json"],
            "examples": ["powerbi-cli model dax lint --project build/sales --json"],
            "diagnosticCodes": crate::rules::rules_for_family(crate::rules::RuleFamily::Dax).map(|rule| rule.id).collect::<Vec<_>>(),
            "limitations": ["Static reference lint only; Power BI Desktop remains the compatibility oracle for DAX syntax and semantics."],
            "followUpFields": ["ok", "analysisBoundary", "counts.errors", "counts.warnings", "findings[].code", "validation", "next"]
        }),
        json!({
            "path": "model dax execute",
            "aliases": ["model dax query"],
            "usage": "POWERBI_DESKTOP_ORACLE=1 powerbi-cli model dax execute --project <project-dir-or.pbip-or.pbix> (--query <dax> | --query-file <path|->) --allow-data-read [--enable-oracle] [--max-rows <1..100000>] [--max-cell-chars <1..1000000>] [--timeout-ms <1000..300000>] --json",
            "summary": "Execute a bounded read-only DAX EVALUATE query against the exact already-open Power BI Desktop semantic model",
            "tags": ["tmdl", "semantic-model", "dax", "query", "desktop", "oracle", "read-only", "data-read", "agent", "no-fallback"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "returnsModelData": true,
            "explicitOptIn": ["POWERBI_DESKTOP_ORACLE=1", "--enable-oracle", "--allow-data-read"],
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.dax.execute.v2",
            "timeoutContract": "timeout-ms is one end-to-end watchdog for exact Desktop/model discovery, in-bridge PID/creation/workspace/port revalidation, connection, and bounded query execution",
            "flags": ["--project <project-dir-or.pbip-or.pbix>", "--query <dax>", "--query-file <path|->", "--allow-data-read", "--enable-oracle", "--max-rows <1..100000>", "--max-cell-chars <1..1000000>", "--timeout-ms <1000..300000>", "--json", "--format json"],
            "examples": ["POWERBI_DESKTOP_ORACLE=1 powerbi-cli model dax execute --project build/sales --query-file checks/total-revenue.dax --allow-data-read --json", "POWERBI_DESKTOP_ORACLE=1 powerbi-cli model dax query --project build/sales --query \"EVALUATE ROW(\\\"Value\\\", 1)\" --allow-data-read --max-rows 10 --json"],
            "limitations": ["Windows and an already-open exact PBIP or PBIX document match are required; the command never launches Desktop.", "Only EVALUATE or DEFINE ... EVALUATE query forms are accepted; XMLA/model mutations are refused.", "Returned rows can contain sensitive model data and are bounded but not redacted.", "The local Desktop Analysis Services endpoint and bundled ADOMD client are implementation details and may change with Desktop."],
            "followUpFields": ["ok", "exitCode", "document.kind", "document.path", "query.fingerprint", "query.textReturned", "safety", "limits", "stage", "engine.desktopProcessId", "engine.modelProcessId", "columns", "rows", "counts", "truncation", "runtime.temporaryFilesRemoved", "diagnostics", "validation", "next"]
        }),
        json!({
            "path": "model live export-tmdl",
            "usage": "POWERBI_DESKTOP_ORACLE=1 powerbi-cli model live export-tmdl --document <project-dir-or.pbip-or.pbix> --out-dir <fresh-dir> --allow-model-read [--enable-oracle] [--timeout-ms <1000..300000>] --json",
            "summary": "Export the semantic model of one exact already-open Desktop PBIP/PBIX document to a fresh validated TMDL definition through the pinned local Microsoft MCP",
            "tags": ["tmdl", "semantic-model", "pbix", "pbip", "desktop", "modeling-mcp", "read-only", "model-read", "agent", "no-fallback"],
            "readOnly": true,
            "mutates": false,
            "writesOutput": true,
            "writesDataCache": false,
            "returnsModelData": false,
            "returnsModelMetadata": true,
            "explicitOptIn": ["POWERBI_DESKTOP_ORACLE=1", "--enable-oracle", "--allow-model-read"],
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.live.export-tmdl.v1",
            "timeoutContract": "timeout-ms is one end-to-end watchdog for discovery, exact endpoint revalidation, MCP handshake/connect/export, bounded output validation, publication, and a reserved MCP cleanup budget",
            "flags": ["--document <project-dir-or.pbip-or.pbix>", "--out-dir <fresh-dir>", "--allow-model-read", "--enable-oracle", "--timeout-ms <1000..300000>", "--json", "--format json"],
            "examples": ["POWERBI_DESKTOP_ORACLE=1 powerbi-cli model live export-tmdl --document SourceProfile.pbix --out-dir build/source-profile-model --allow-model-read --json"],
            "limitations": ["Windows and an already-open exact PBIP or PBIX document match are required; the command never launches Desktop.", "The pinned local Microsoft Modeling MCP integration must be installed and pass its exact handshake.", "The output is semantic-model TMDL only, not report pages and not a full PBIX-to-PBIP conversion.", "TMDL contains DAX, Power Query source expressions, and possibly small static table values; explicit model-read consent and review are required.", "The destination must be a fresh child of an existing ordinary directory; export occurs in a private sibling quarantine and is published only after bounded shape, UTF-8, link/reparse, and credential-like-text validation."],
            "followUpFields": ["ok", "exitCode", "document.kind", "document.path", "output.kind", "output.root", "output.definition", "output.fileCount", "output.totalBytes", "output.sha256", "engine.desktopProcessId", "engine.modelProcessId", "integration.server", "integration.cleanup", "safety", "limits", "validation", "instructions", "next"]
        }),
        json!({
            "path": "model advanced inventory",
            "aliases": ["model inventory"],
            "usage": "powerbi-cli model advanced inventory --project <project-dir-or.pbip> --json",
            "summary": "Inventory advanced TMDL folders for roles, perspectives, cultures, and named expressions",
            "tags": ["tmdl", "semantic-model", "advanced", "roles", "rls", "perspectives", "cultures", "expressions", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.advanced.inventory.v1",
            "flags": ["--project <project-dir-or.pbip>", "--json", "--format json"],
            "examples": ["powerbi-cli model advanced inventory --project build/sales --json"],
            "followUpFields": ["families[].family", "families[].records[].handle", "validation", "next"]
        }),
        json!({
            "path": "model roles list",
            "aliases": ["model rls list", "model role list"],
            "usage": "powerbi-cli model roles list --project <project-dir-or.pbip> [--include-raw] --json",
            "summary": "List role/RLS TMDL blocks by stable handle",
            "tags": ["tmdl", "semantic-model", "roles", "rls", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.roles.list.v1",
            "flags": ["--project <project-dir-or.pbip>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model roles list --project build/sales --json"],
            "followUpFields": ["records[].handle", "records[].summary", "validation", "next"]
        }),
        json!({
            "path": "model perspectives list",
            "usage": "powerbi-cli model perspectives list --project <project-dir-or.pbip> [--include-raw] --json",
            "summary": "List perspective TMDL blocks by stable handle",
            "tags": ["tmdl", "semantic-model", "perspectives", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.perspectives.list.v1",
            "flags": ["--project <project-dir-or.pbip>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model perspectives list --project build/sales --json"],
            "followUpFields": ["records[].handle", "records[].summary", "validation", "next"]
        }),
        json!({
            "path": "model cultures list",
            "aliases": ["model translations list"],
            "usage": "powerbi-cli model cultures list --project <project-dir-or.pbip> [--include-raw] --json",
            "summary": "List culture/translation TMDL blocks by stable handle",
            "tags": ["tmdl", "semantic-model", "cultures", "translations", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.cultures.list.v1",
            "flags": ["--project <project-dir-or.pbip>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model cultures list --project build/sales --json"],
            "followUpFields": ["records[].handle", "records[].summary", "validation", "next"]
        }),
        json!({
            "path": "model expressions list",
            "aliases": ["model named-expressions list"],
            "usage": "powerbi-cli model expressions list --project <project-dir-or.pbip> [--include-raw] --json",
            "summary": "List named expression TMDL blocks by stable handle",
            "tags": ["tmdl", "semantic-model", "expressions", "named-expressions", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.expressions.list.v1",
            "flags": ["--project <project-dir-or.pbip>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model expressions list --project build/sales --json"],
            "followUpFields": ["records[].handle", "records[].summary", "validation", "next"]
        }),
        json!({
            "path": "model roles show",
            "aliases": ["model rls show", "model role show"],
            "usage": "powerbi-cli model roles show --project <project-dir-or.pbip> (--handle <role-handle> | --name <role-name>) [--include-raw] --json",
            "summary": "Show one role/RLS TMDL block by stable handle or exact name",
            "tags": ["tmdl", "semantic-model", "roles", "rls", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.roles.show.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <role-handle>", "--name <role-name>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model roles show --project build/sales --handle role:Safety --json"],
            "followUpFields": ["record.handle", "record.summary", "record.block", "validation", "next"]
        }),
        json!({
            "path": "model perspectives show",
            "usage": "powerbi-cli model perspectives show --project <project-dir-or.pbip> (--handle <perspective-handle> | --name <perspective-name>) [--include-raw] --json",
            "summary": "Show one perspective TMDL block by stable handle or exact name",
            "tags": ["tmdl", "semantic-model", "perspectives", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.perspectives.show.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <perspective-handle>", "--name <perspective-name>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model perspectives show --project build/sales --handle perspective:Executive --json"],
            "followUpFields": ["record.handle", "record.summary", "record.block", "validation", "next"]
        }),
        json!({
            "path": "model cultures show",
            "aliases": ["model translations show"],
            "usage": "powerbi-cli model cultures show --project <project-dir-or.pbip> (--handle <culture-handle> | --name <culture-name>) [--include-raw] --json",
            "summary": "Show one culture/translation TMDL block by stable handle or exact name",
            "tags": ["tmdl", "semantic-model", "cultures", "translations", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.cultures.show.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <culture-handle>", "--name <culture-name>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model cultures show --project build/sales --handle culture:de-CH --json"],
            "followUpFields": ["record.handle", "record.summary", "record.block", "validation", "next"]
        }),
        json!({
            "path": "model expressions show",
            "aliases": ["model named-expressions show"],
            "usage": "powerbi-cli model expressions show --project <project-dir-or.pbip> (--handle <expression-handle> | --name <expression-name>) [--include-raw] --json",
            "summary": "Show one named expression TMDL block by stable handle or exact name",
            "tags": ["tmdl", "semantic-model", "expressions", "named-expressions", "readback", "agent"],
            "readOnly": true,
            "mutates": false,
            "writesDataCache": false,
            "stability": "alpha-output",
            "proofLevel": "unit-smoke",
            "outputSchema": "powerbi-cli.model.expressions.show.v1",
            "flags": ["--project <project-dir-or.pbip>", "--handle <expression-handle>", "--name <expression-name>", "--include-raw", "--json", "--format json"],
            "examples": ["powerbi-cli model expressions show --project build/sales --handle expression:RefreshDate --json"],
            "followUpFields": ["record.handle", "record.summary", "record.block", "validation", "next"]
        }),
    ]
}
